# =======================================================
# CONFIGURACION DE RED Y BASE DE DATOS - ADIVINA QUIEN
# =======================================================

# Direccion IP del Servidor Socket
# - Para jugar en la misma computadora: 127.0.0.1
# - Para jugar en red local / modem / hotspot: Cambia por la IP local del Servidor (ej. 192.168.1.15)
servidor_ip=127.0.0.1

# Puerto de comunicacion Socket (por defecto 5000)
servidor_puerto=5000

# Parametros de Base de Datos MySQL / MariaDB
db_url=jdbc:mysql://localhost:3306/adivina_quien
db_usuario=root
db_password=root